// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.steward_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_steward_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_steward_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "steward_ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "steward_ffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_steward_ffi_checksum_func_open_guardian(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_generate_heartbeat_key(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_heartbeat_pubkey(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_is_lapsed(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_sign_heartbeat(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_verify_heartbeat(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_split_authority(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_seal_share(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_aggregate_signature(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_build_signing_package(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_random_randomizer_hex(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_randomized_verifying_key_hex(
    ): Int
    external fun uniffi_steward_ffi_checksum_func_verify_aggregate(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_adjourn(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_handle_relay_message(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_identifier(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_pending_count(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_round1(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_round2(
    ): Int
    external fun uniffi_steward_ffi_checksum_method_guardian_wipe(
    ): Int
    external fun ffi_steward_ffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "steward_ffi"))
        
    }
    external fun uniffi_steward_ffi_fn_clone_guardian(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_steward_ffi_fn_free_guardian(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_steward_ffi_fn_method_guardian_adjourn(`ptr`: Long,`sessionId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_steward_ffi_fn_method_guardian_handle_relay_message(`ptr`: Long,`sessionId`: RustBuffer.ByValue,`incomingMsgHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_method_guardian_identifier(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_method_guardian_pending_count(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun uniffi_steward_ffi_fn_method_guardian_round1(`ptr`: Long,`sessionId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_method_guardian_round2(`ptr`: Long,`sessionId`: RustBuffer.ByValue,`signingPackageJson`: RustBuffer.ByValue,`randomizerLeHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_method_guardian_wipe(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_steward_ffi_fn_func_open_guardian(`sealedBlob`: RustBuffer.ByValue,`passphrase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_steward_ffi_fn_func_generate_heartbeat_key(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_heartbeat_pubkey(`skHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_is_lapsed(`latest`: Long,`interval`: Long,`grace`: Long,`now`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_steward_ffi_fn_func_sign_heartbeat(`skHex`: RustBuffer.ByValue,`vaultId`: RustBuffer.ByValue,`time`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_verify_heartbeat(`pubkeyHex`: RustBuffer.ByValue,`vaultId`: RustBuffer.ByValue,`time`: Long,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_steward_ffi_fn_func_split_authority(`n`: Short,`t`: Short,`askHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_seal_share(`secretShareJson`: RustBuffer.ByValue,`passphrase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_aggregate_signature(`round2Replies`: RustBuffer.ByValue,`signingPackageJson`: RustBuffer.ByValue,`sighashHex`: RustBuffer.ByValue,`randomizerLeHex`: RustBuffer.ByValue,`publicKeyPackageJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_build_signing_package(`round1Replies`: RustBuffer.ByValue,`sighashHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_random_randomizer_hex(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_randomized_verifying_key_hex(`randomizerLeHex`: RustBuffer.ByValue,`publicKeyPackageJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_steward_ffi_fn_func_verify_aggregate(`sighashHex`: RustBuffer.ByValue,`randomizerLeHex`: RustBuffer.ByValue,`publicKeyPackageJson`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_steward_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_steward_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_steward_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_steward_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_steward_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_steward_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_steward_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_steward_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_steward_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_steward_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_steward_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_steward_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_steward_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_steward_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_steward_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_steward_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_steward_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_steward_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_steward_ffi_checksum_func_open_guardian() != 50376) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_generate_heartbeat_key() != 35325) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_heartbeat_pubkey() != 38735) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_is_lapsed() != 18647) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_sign_heartbeat() != 30508) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_verify_heartbeat() != 53228) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_split_authority() != 35616) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_seal_share() != 59710) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_aggregate_signature() != 63799) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_build_signing_package() != 30401) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_random_randomizer_hex() != 61912) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_randomized_verifying_key_hex() != 32116) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_func_verify_aggregate() != 16335) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_adjourn() != 16491) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_handle_relay_message() != 36894) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_identifier() != 42066) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_pending_count() != 13566) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_round1() != 19253) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_round2() != 51063) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_steward_ffi_checksum_method_guardian_wipe() != 48537) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    fun lift(value: Int): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * A live guardian: one decrypted FROST share plus its per-session single-use
 * nonces. The `KeyPackage` stays **inside** this object for its whole lifetime and
 * is never exposed across the FFI boundary. The inner state is behind a `Mutex` so
 * the object is `Send + Sync` (UniFFI hands the app an `Arc<Guardian>`).
 */
public interface GuardianInterface {
    
    /**
     * Discard any live round-1 state for `session_id` (the coordinator adjourned it).
     */
    fun `adjourn`(`sessionId`: kotlin.String)
    
    /**
     * The "the app only moves bytes" entry point. Feed it the hex a relay
     * `/session/{id}/recv` returned (the coordinator's enveloped `Message`); it runs
     * the right round and returns a [`RelayAction`] describing what to POST (if
     * anything) to `/session/{id}/send`. The app never parses FROST.
     */
    fun `handleRelayMessage`(`sessionId`: kotlin.String, `incomingMsgHex`: kotlin.String): RelayAction
    
    /**
     * This guardian's FROST identifier, as canonical hex.
     */
    fun `identifier`(): kotlin.String
    
    /**
     * Number of sessions with live (unconsumed) round-1 nonces. `0` between
     * ceremonies; the single-use discipline is observable here.
     */
    fun `pendingCount`(): kotlin.UInt
    
    /**
     * Round 1: commit. Mints single-use signing nonces, stores them under
     * `session_id`, and returns the `Round1Reply` message JSON the coordinator
     * expects on the relay. Throws [`StewardError::Wiped`] after [`wipe`](Self::wipe).
     */
    fun `round1`(`sessionId`: kotlin.String): kotlin.String
    
    /**
     * Round 2: sign the coordinator's `signing_package` (JSON) under the ZIP-312
     * randomizer α (`randomizer_le_hex`, 32-byte little-endian) **by value**, then
     * delete this session's nonces. Returns the `Round2Reply` message JSON. A
     * missing or already-consumed session throws [`StewardError::NoSession`].
     */
    fun `round2`(`sessionId`: kotlin.String, `signingPackageJson`: kotlin.String, `randomizerLeHex`: kotlin.String): kotlin.String
    
    /**
     * Zeroize and drop all key material (the `KeyPackage` and every live nonce). The
     * handle is inert afterwards — any further round call throws
     * [`StewardError::Wiped`]. Call this on lock/logout.
     */
    fun `wipe`()
    
    companion object
}

/**
 * A live guardian: one decrypted FROST share plus its per-session single-use
 * nonces. The `KeyPackage` stays **inside** this object for its whole lifetime and
 * is never exposed across the FFI boundary. The inner state is behind a `Mutex` so
 * the object is `Send + Sync` (UniFFI hands the app an `Arc<Guardian>`).
 */
open class Guardian: Disposable, AutoCloseable, GuardianInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    /**
     * Whether the current object has been destroyed and its reference is gone in the Rust side.
     */
    val uniffiIsDestroyed: Boolean get() = wasDestroyed.get()

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_steward_ffi_fn_free_guardian(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_steward_ffi_fn_clone_guardian(handle, status)
        }
    }

    
    /**
     * Discard any live round-1 state for `session_id` (the coordinator adjourned it).
     */override fun `adjourn`(`sessionId`: kotlin.String)
        = 
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_adjourn(
        it,
        
        FfiConverterString.lower(`sessionId`),_status)
}
    }
    
    

    
    /**
     * The "the app only moves bytes" entry point. Feed it the hex a relay
     * `/session/{id}/recv` returned (the coordinator's enveloped `Message`); it runs
     * the right round and returns a [`RelayAction`] describing what to POST (if
     * anything) to `/session/{id}/send`. The app never parses FROST.
     */
    @Throws(StewardException::class)override fun `handleRelayMessage`(`sessionId`: kotlin.String, `incomingMsgHex`: kotlin.String): RelayAction {
            return FfiConverterTypeRelayAction.lift(
    callWithHandle {
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_handle_relay_message(
        it,
        
        FfiConverterString.lower(`sessionId`),
        FfiConverterString.lower(`incomingMsgHex`),_status)
}
    }
    )
    }
    

    
    /**
     * This guardian's FROST identifier, as canonical hex.
     */override fun `identifier`(): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_identifier(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Number of sessions with live (unconsumed) round-1 nonces. `0` between
     * ceremonies; the single-use discipline is observable here.
     */override fun `pendingCount`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_pending_count(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Round 1: commit. Mints single-use signing nonces, stores them under
     * `session_id`, and returns the `Round1Reply` message JSON the coordinator
     * expects on the relay. Throws [`StewardError::Wiped`] after [`wipe`](Self::wipe).
     */
    @Throws(StewardException::class)override fun `round1`(`sessionId`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_round1(
        it,
        
        FfiConverterString.lower(`sessionId`),_status)
}
    }
    )
    }
    

    
    /**
     * Round 2: sign the coordinator's `signing_package` (JSON) under the ZIP-312
     * randomizer α (`randomizer_le_hex`, 32-byte little-endian) **by value**, then
     * delete this session's nonces. Returns the `Round2Reply` message JSON. A
     * missing or already-consumed session throws [`StewardError::NoSession`].
     */
    @Throws(StewardException::class)override fun `round2`(`sessionId`: kotlin.String, `signingPackageJson`: kotlin.String, `randomizerLeHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_round2(
        it,
        
        FfiConverterString.lower(`sessionId`),
        FfiConverterString.lower(`signingPackageJson`),
        FfiConverterString.lower(`randomizerLeHex`),_status)
}
    }
    )
    }
    

    
    /**
     * Zeroize and drop all key material (the `KeyPackage` and every live nonce). The
     * handle is inert afterwards — any further round call throws
     * [`StewardError::Wiped`]. Call this on lock/logout.
     */override fun `wipe`()
        = 
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_method_guardian_wipe(
        it,
        _status)
}
    }
    
    

    

    


    
    
    /**
     * @suppress
     */
    companion object
    
}


/**
 * @suppress
 */
public object FfiConverterTypeGuardian: FfiConverter<Guardian, Long> {
    override fun lower(value: Guardian): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): Guardian {
        return Guardian(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): Guardian {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: Guardian) = 8UL

    override fun write(value: Guardian, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



/**
 * One guardian's share, ready to hand to that guardian (who then [`seal_share`]s
 * it under their own passphrase).
 *
 * [`seal_share`]: crate::seal_share
 */
data class GuardianShare (
    /**
     * The guardian's FROST identifier, canonical hex.
     */
    var `identifierHex`: kotlin.String
    , 
    /**
     * The guardian's `SecretShare` as JSON — the exact bytes [`seal_share`] expects.
     *
     * [`seal_share`]: crate::seal_share
     */
    var `secretShareJson`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeGuardianShare: FfiConverterRustBuffer<GuardianShare> {
    override fun read(buf: ByteBuffer): GuardianShare {
        return GuardianShare(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: GuardianShare) = (
            FfiConverterString.allocationSize(value.`identifierHex`) +
            FfiConverterString.allocationSize(value.`secretShareJson`)
    )

    override fun write(value: GuardianShare, buf: ByteBuffer) {
            FfiConverterString.write(value.`identifierHex`, buf)
            FfiConverterString.write(value.`secretShareJson`, buf)
    }
}



/**
 * A freshly generated Ed25519 heartbeat keypair, returned to the owner at vault
 * setup. Record the `pubkey_hex` on the vault; keep the `secret_hex` on-device and
 * use it to sign each proof-of-life.
 */
data class HeartbeatKey (
    /**
     * 32-byte Ed25519 secret-key **seed**, hex (RFC 8032; never leaves the device).
     */
    var `secretHex`: kotlin.String
    , 
    /**
     * 32-byte Ed25519 public key, hex — publish this on the vault record.
     */
    var `pubkeyHex`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHeartbeatKey: FfiConverterRustBuffer<HeartbeatKey> {
    override fun read(buf: ByteBuffer): HeartbeatKey {
        return HeartbeatKey(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: HeartbeatKey) = (
            FfiConverterString.allocationSize(value.`secretHex`) +
            FfiConverterString.allocationSize(value.`pubkeyHex`)
    )

    override fun write(value: HeartbeatKey, buf: ByteBuffer) {
            FfiConverterString.write(value.`secretHex`, buf)
            FfiConverterString.write(value.`pubkeyHex`, buf)
    }
}



/**
 * The instruction returned by [`Guardian::handle_relay_message`] telling the app
 * what to do next. The caller just moves bytes: if `action == "send"`, POST
 * `{ to, msg_hex }` to `/session/{id}/send`; if `"none"`, there is nothing to send.
 */
data class RelayAction (
    /**
     * `"send"` (there is a reply to POST) or `"none"` (adjourned / nothing to send).
     */
    var `action`: kotlin.String
    , 
    /**
     * Destination for the relay `SendBody.to`; `None` means the coordinator.
     */
    var `to`: kotlin.String?
    , 
    /**
     * The reply to POST as `SendBody.msg_hex` (hex of the `Message` JSON), or `None`.
     */
    var `msgHex`: kotlin.String?
    , 
    /**
     * Whether this session is finished for the guardian (stop polling it).
     */
    var `done`: kotlin.Boolean
    , 
    /**
     * `"round1"` | `"round2"` | `"adjourn"` — for UX/logging only.
     */
    var `kind`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRelayAction: FfiConverterRustBuffer<RelayAction> {
    override fun read(buf: ByteBuffer): RelayAction {
        return RelayAction(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: RelayAction) = (
            FfiConverterString.allocationSize(value.`action`) +
            FfiConverterOptionalString.allocationSize(value.`to`) +
            FfiConverterOptionalString.allocationSize(value.`msgHex`) +
            FfiConverterBoolean.allocationSize(value.`done`) +
            FfiConverterString.allocationSize(value.`kind`)
    )

    override fun write(value: RelayAction, buf: ByteBuffer) {
            FfiConverterString.write(value.`action`, buf)
            FfiConverterOptionalString.write(value.`to`, buf)
            FfiConverterOptionalString.write(value.`msgHex`, buf)
            FfiConverterBoolean.write(value.`done`, buf)
            FfiConverterString.write(value.`kind`, buf)
    }
}



/**
 * The output of [`split_authority`]: what the owner publishes + distributes.
 */
data class VaultKeygen (
    /**
     * The Orchard spend-validating key `ak` (== the FROST group verifying key),
     * 32-byte hex. The signer derives the vault's UFVK / receiving address from this.
     */
    var `groupAkHex`: kotlin.String
    , 
    /**
     * The FROST `PublicKeyPackage` as JSON — publish this to the relay's vault record.
     */
    var `publicKeyPackageJson`: kotlin.String
    , 
    /**
     * One share per guardian (`n` of them), keyed by identifier.
     */
    var `shares`: List<GuardianShare>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeVaultKeygen: FfiConverterRustBuffer<VaultKeygen> {
    override fun read(buf: ByteBuffer): VaultKeygen {
        return VaultKeygen(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeGuardianShare.read(buf),
        )
    }

    override fun allocationSize(value: VaultKeygen) = (
            FfiConverterString.allocationSize(value.`groupAkHex`) +
            FfiConverterString.allocationSize(value.`publicKeyPackageJson`) +
            FfiConverterSequenceTypeGuardianShare.allocationSize(value.`shares`)
    )

    override fun write(value: VaultKeygen, buf: ByteBuffer) {
            FfiConverterString.write(value.`groupAkHex`, buf)
            FfiConverterString.write(value.`publicKeyPackageJson`, buf)
            FfiConverterSequenceTypeGuardianShare.write(value.`shares`, buf)
    }
}





/**
 * Errors returned by the Steward mobile SDK.
 */
sealed class StewardException: kotlin.Exception() {
    
    /**
     * JSON (de)serialization failed — a malformed share / package / message.
     */
    class Json(
        
        /**
         * Underlying serde_json message.
         */
        val `msg`: kotlin.String
        ) : StewardException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    /**
     * Hex decoding failed (bad characters, or the wrong length for a fixed field).
     */
    class Hex(
        
        /**
         * Underlying hex message.
         */
        val `msg`: kotlin.String
        ) : StewardException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    /**
     * Key-derivation (Argon2id) failure — e.g. invalid KDF parameters.
     */
    class Kdf(
        
        /**
         * Underlying KDF message.
         */
        val `msg`: kotlin.String
        ) : StewardException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    /**
     * The keystore could not be opened: **wrong passphrase or a corrupted blob**
     * (indistinguishable by design — a wrong passphrase must not be told apart
     * from tampering).
     */
    class BadPassphrase(
        ) : StewardException() {
        override val message
            get() = ""
    }
    
    /**
     * A wrapped FROST error from [`steward_core`] (keygen / commit / sign / aggregate).
     */
    class Frost(
        
        /**
         * Underlying FROST message.
         */
        val `msg`: kotlin.String
        ) : StewardException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    /**
     * A malformed input: bad length, unknown blob version, a non-32-byte field, ...
     */
    class Format(
        
        /**
         * What was malformed.
         */
        val `msg`: kotlin.String
        ) : StewardException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    /**
     * The [`Guardian`](crate::Guardian) handle has been wiped; no key material remains.
     */
    class Wiped(
        ) : StewardException() {
        override val message
            get() = ""
    }
    
    /**
     * No live round-1 nonces for this session (round 1 was skipped, or the nonces
     * were already consumed by a round 2 — the single-use discipline).
     */
    class NoSession(
        ) : StewardException() {
        override val message
            get() = ""
    }
    
    /**
     * A guardian received a message it should never be sent (a coordinator-bound reply).
     */
    class Unexpected(
        ) : StewardException() {
        override val message
            get() = ""
    }
    
    /**
     * The platform RNG failed.
     */
    class Rng(
        
        /**
         * Underlying RNG message.
         */
        val `msg`: kotlin.String
        ) : StewardException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<StewardException> {
        override fun lift(error_buf: RustBuffer.ByValue): StewardException = FfiConverterTypeStewardError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeStewardError : FfiConverterRustBuffer<StewardException> {
    override fun read(buf: ByteBuffer): StewardException {
        

        return when(buf.getInt()) {
            1 -> StewardException.Json(
                FfiConverterString.read(buf),
                )
            2 -> StewardException.Hex(
                FfiConverterString.read(buf),
                )
            3 -> StewardException.Kdf(
                FfiConverterString.read(buf),
                )
            4 -> StewardException.BadPassphrase()
            5 -> StewardException.Frost(
                FfiConverterString.read(buf),
                )
            6 -> StewardException.Format(
                FfiConverterString.read(buf),
                )
            7 -> StewardException.Wiped()
            8 -> StewardException.NoSession()
            9 -> StewardException.Unexpected()
            10 -> StewardException.Rng(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: StewardException): ULong {
        return when(value) {
            is StewardException.Json -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is StewardException.Hex -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is StewardException.Kdf -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is StewardException.BadPassphrase -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is StewardException.Frost -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is StewardException.Format -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is StewardException.Wiped -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is StewardException.NoSession -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is StewardException.Unexpected -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is StewardException.Rng -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: StewardException, buf: ByteBuffer) {
        when(value) {
            is StewardException.Json -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is StewardException.Hex -> {
                buf.putInt(2)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is StewardException.Kdf -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is StewardException.BadPassphrase -> {
                buf.putInt(4)
                Unit
            }
            is StewardException.Frost -> {
                buf.putInt(5)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is StewardException.Format -> {
                buf.putInt(6)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is StewardException.Wiped -> {
                buf.putInt(7)
                Unit
            }
            is StewardException.NoSession -> {
                buf.putInt(8)
                Unit
            }
            is StewardException.Unexpected -> {
                buf.putInt(9)
                Unit
            }
            is StewardException.Rng -> {
                buf.putInt(10)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeGuardianShare: FfiConverterRustBuffer<List<GuardianShare>> {
    override fun read(buf: ByteBuffer): List<GuardianShare> {
        val len = buf.getInt()
        return List<GuardianShare>(len) {
            FfiConverterTypeGuardianShare.read(buf)
        }
    }

    override fun allocationSize(value: List<GuardianShare>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeGuardianShare.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<GuardianShare>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeGuardianShare.write(it, buf)
        }
    }
}
        /**
         * Open a sealed share blob into a live [`Guardian`] handle.
         *
         * Decrypts with `passphrase`, rebuilds the `KeyPackage`, and returns a handle that
         * keeps the key material inside the object (never returned to the app). A wrong
         * passphrase (or a tampered blob) throws [`StewardError::BadPassphrase`]. Unlock
         * **once** (not per relay poll); call [`Guardian::wipe`] on lock/logout.
         */
    @Throws(StewardException::class) fun `openGuardian`(`sealedBlob`: kotlin.String, `passphrase`: kotlin.String): Guardian {
            return FfiConverterTypeGuardian.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_open_guardian(
    
        
        FfiConverterString.lower(`sealedBlob`),
        FfiConverterString.lower(`passphrase`),_status)
}
    )
    }
    

        /**
         * Generate a fresh Ed25519 heartbeat keypair (owner setup). The secret is 32
         * random bytes from the platform CSPRNG; the public key is derived from it.
         */ fun `generateHeartbeatKey`(): HeartbeatKey {
            return FfiConverterTypeHeartbeatKey.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_generate_heartbeat_key(
    
        _status)
}
    )
    }
    

        /**
         * Derive the hex Ed25519 public key from a hex secret seed.
         */
    @Throws(StewardException::class) fun `heartbeatPubkey`(`skHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_heartbeat_pubkey(
    
        
        FfiConverterString.lower(`skHex`),_status)
}
    )
    }
    

        /**
         * Whether the dead-man's-switch has **lapsed** at `now`, judged purely from the
         * owner's own signed timestamp: `now > latest + interval + grace` (saturating).
         * This is the authoritative inheritance gate a guardian computes on its own clock
         * from a heartbeat it verified itself — never trusting a relay's state flag.
         */ fun `isLapsed`(`latest`: kotlin.ULong, `interval`: kotlin.ULong, `grace`: kotlin.ULong, `now`: kotlin.ULong): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_is_lapsed(
    
        
        FfiConverterULong.lower(`latest`),
        FfiConverterULong.lower(`interval`),
        FfiConverterULong.lower(`grace`),
        FfiConverterULong.lower(`now`),_status)
}
    )
    }
    

        /**
         * Sign a proof-of-life for `vault_id` at `time` (unix seconds) with the owner's
         * hex heartbeat secret seed. Deterministic (RFC 8032): identical inputs → identical
         * bytes. Returns the 64-byte signature as hex.
         */
    @Throws(StewardException::class) fun `signHeartbeat`(`skHex`: kotlin.String, `vaultId`: kotlin.String, `time`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_sign_heartbeat(
    
        
        FfiConverterString.lower(`skHex`),
        FfiConverterString.lower(`vaultId`),
        FfiConverterULong.lower(`time`),_status)
}
    )
    }
    

        /**
         * Verify a hex heartbeat signature against the vault's recorded hex public key and
         * the canonical message. Returns `false` — never throws — on any decode or
         * verification failure. A relay has no secret key, so it cannot forge a `true` here.
         */ fun `verifyHeartbeat`(`pubkeyHex`: kotlin.String, `vaultId`: kotlin.String, `time`: kotlin.ULong, `sigHex`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_verify_heartbeat(
    
        
        FfiConverterString.lower(`pubkeyHex`),
        FfiConverterString.lower(`vaultId`),
        FfiConverterULong.lower(`time`),
        FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

        /**
         * Split the vault spend authority into `t`-of-`n` guardian shares (trusted-dealer).
         *
         * `n` = total guardians, `t` = threshold (`1 <= t <= n`). If `ask_hex` is `None` a
         * fresh spend authority is generated on-device and dropped after the split (ideal
         * trusted-dealer hygiene — the monolithic key never exists anywhere afterwards). If
         * `Some`, it is the 32-byte hex of an existing RedPallas `ask` (e.g. one the signer
         * derived), so the resulting vault address matches a pre-derived one.
         *
         * The split is routed through even-Y normalization by [`steward_core::keys`], so
         * `ak` always has the even Y coordinate RedPallas/Orchard require.
         */
    @Throws(StewardException::class) fun `splitAuthority`(`n`: kotlin.UShort, `t`: kotlin.UShort, `askHex`: kotlin.String?): VaultKeygen {
            return FfiConverterTypeVaultKeygen.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_split_authority(
    
        
        FfiConverterUShort.lower(`n`),
        FfiConverterUShort.lower(`t`),
        FfiConverterOptionalString.lower(`askHex`),_status)
}
    )
    }
    

        /**
         * Seal a guardian's secret share for encrypted-at-rest storage.
         *
         * `secret_share_json` is the JSON of a [`steward_core`] `SecretShare` — exactly the
         * `GuardianShare.secret_share_json` the vault dealer produced in
         * [`split_authority`](crate::split_authority). Returns a self-describing sealed-blob
         * JSON string; store it wherever the platform keeps app data (Keychain / Keystore /
         * files). A malformed share is rejected here.
         */
    @Throws(StewardException::class) fun `sealShare`(`secretShareJson`: kotlin.String, `passphrase`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_seal_share(
    
        
        FfiConverterString.lower(`secretShareJson`),
        FfiConverterString.lower(`passphrase`),_status)
}
    )
    }
    

        /**
         * Coordinator: aggregate the guardians' round-2 replies into the final 64-byte
         * RedPallas signature (hex), re-randomized by α.
         *
         * Each element of `round2_replies` is a `Round2Reply` message JSON — exactly what
         * [`Guardian::round2`](crate::Guardian::round2) returns. The result verifies against
         * `rk = ak + [α]G` (see [`verify_aggregate`]) — **not** the un-randomized group key.
         */
    @Throws(StewardException::class) fun `aggregateSignature`(`round2Replies`: List<kotlin.String>, `signingPackageJson`: kotlin.String, `sighashHex`: kotlin.String, `randomizerLeHex`: kotlin.String, `publicKeyPackageJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_aggregate_signature(
    
        
        FfiConverterSequenceString.lower(`round2Replies`),
        FfiConverterString.lower(`signingPackageJson`),
        FfiConverterString.lower(`sighashHex`),
        FfiConverterString.lower(`randomizerLeHex`),
        FfiConverterString.lower(`publicKeyPackageJson`),_status)
}
    )
    }
    

        /**
         * Coordinator: assemble the `SigningPackage` (JSON) over `sighash_hex` from the
         * guardians' round-1 replies.
         *
         * Each element of `round1_replies` is a `Round1Reply` message JSON — exactly what
         * [`Guardian::round1`](crate::Guardian::round1) returns. Pass the `t` you selected.
         */
    @Throws(StewardException::class) fun `buildSigningPackage`(`round1Replies`: List<kotlin.String>, `sighashHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_build_signing_package(
    
        
        FfiConverterSequenceString.lower(`round1Replies`),
        FfiConverterString.lower(`sighashHex`),_status)
}
    )
    }
    

        /**
         * Generate a uniformly random ZIP-312 randomizer α (32-byte little-endian hex).
         *
         * **Simulation / testing only.** In production α is fixed by the transaction builder
         * (`zcash-sign`) and must be threaded by value; a freshly generated α would not
         * match the transaction's `rk` and the signature would be unusable on-chain.
         */ fun `randomRandomizerHex`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_random_randomizer_hex(
    
        _status)
}
    )
    }
    

        /**
         * The randomized group verifying key `rk = ak + [α]G` (32-byte hex) for the given
         * randomizer and public package.
         */
    @Throws(StewardException::class) fun `randomizedVerifyingKeyHex`(`randomizerLeHex`: kotlin.String, `publicKeyPackageJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_randomized_verifying_key_hex(
    
        
        FfiConverterString.lower(`randomizerLeHex`),
        FfiConverterString.lower(`publicKeyPackageJson`),_status)
}
    )
    }
    

        /**
         * Verify a 64-byte hex signature against `rk = ak + [α]G` for the given randomizer
         * and public package — the same check the coordinator does before broadcasting.
         * Returns `false` on any decode/verify failure (only structural errors throw).
         */
    @Throws(StewardException::class) fun `verifyAggregate`(`sighashHex`: kotlin.String, `randomizerLeHex`: kotlin.String, `publicKeyPackageJson`: kotlin.String, `sigHex`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(StewardException) { _status ->
    UniffiLib.uniffi_steward_ffi_fn_func_verify_aggregate(
    
        
        FfiConverterString.lower(`sighashHex`),
        FfiConverterString.lower(`randomizerLeHex`),
        FfiConverterString.lower(`publicKeyPackageJson`),
        FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    


