/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_ywallet_App */

#ifndef _Included_app_ywallet_App
#define _Included_app_ywallet_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_ywallet_App
 * Method:    newAccount
 * Signature: ()Lapp/ywallet/ResultInt;
 */
JNIEXPORT jint JNICALL Java_app_ywallet_App_newAccount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
