// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(steward_ffiFFI)
import steward_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_steward_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_steward_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureStewardFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A live guardian: one decrypted FROST share plus its per-session single-use
 * nonces. The `KeyPackage` stays **inside** this object for its whole lifetime and
 * is never exposed across the FFI boundary. The inner state is behind a `Mutex` so
 * the object is `Send + Sync` (UniFFI hands the app an `Arc<Guardian>`).
 */
public protocol GuardianProtocol: AnyObject, Sendable {
    
    /**
     * Discard any live round-1 state for `session_id` (the coordinator adjourned it).
     */
    func adjourn(sessionId: String) 
    
    /**
     * The "the app only moves bytes" entry point. Feed it the hex a relay
     * `/session/{id}/recv` returned (the coordinator's enveloped `Message`); it runs
     * the right round and returns a [`RelayAction`] describing what to POST (if
     * anything) to `/session/{id}/send`. The app never parses FROST.
     */
    func handleRelayMessage(sessionId: String, incomingMsgHex: String) throws  -> RelayAction
    
    /**
     * This guardian's FROST identifier, as canonical hex.
     */
    func identifier()  -> String
    
    /**
     * Number of sessions with live (unconsumed) round-1 nonces. `0` between
     * ceremonies; the single-use discipline is observable here.
     */
    func pendingCount()  -> UInt32
    
    /**
     * Round 1: commit. Mints single-use signing nonces, stores them under
     * `session_id`, and returns the `Round1Reply` message JSON the coordinator
     * expects on the relay. Throws [`StewardError::Wiped`] after [`wipe`](Self::wipe).
     */
    func round1(sessionId: String) throws  -> String
    
    /**
     * Round 2: sign the coordinator's `signing_package` (JSON) under the ZIP-312
     * randomizer α (`randomizer_le_hex`, 32-byte little-endian) **by value**, then
     * delete this session's nonces. Returns the `Round2Reply` message JSON. A
     * missing or already-consumed session throws [`StewardError::NoSession`].
     */
    func round2(sessionId: String, signingPackageJson: String, randomizerLeHex: String) throws  -> String
    
    /**
     * Zeroize and drop all key material (the `KeyPackage` and every live nonce). The
     * handle is inert afterwards — any further round call throws
     * [`StewardError::Wiped`]. Call this on lock/logout.
     */
    func wipe() 
    
}
/**
 * A live guardian: one decrypted FROST share plus its per-session single-use
 * nonces. The `KeyPackage` stays **inside** this object for its whole lifetime and
 * is never exposed across the FFI boundary. The inner state is behind a `Mutex` so
 * the object is `Send + Sync` (UniFFI hands the app an `Arc<Guardian>`).
 */
open class Guardian: GuardianProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_steward_ffi_fn_clone_guardian(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_steward_ffi_fn_free_guardian(handle, $0) }
    }

    

    
    /**
     * Discard any live round-1 state for `session_id` (the coordinator adjourned it).
     */
open func adjourn(sessionId: String)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_adjourn(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),uniffiCallStatus
    )
}
}
    
    /**
     * The "the app only moves bytes" entry point. Feed it the hex a relay
     * `/session/{id}/recv` returned (the coordinator's enveloped `Message`); it runs
     * the right round and returns a [`RelayAction`] describing what to POST (if
     * anything) to `/session/{id}/send`. The app never parses FROST.
     */
open func handleRelayMessage(sessionId: String, incomingMsgHex: String)throws  -> RelayAction  {
    return try  FfiConverterTypeRelayAction_lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_handle_relay_message(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(incomingMsgHex),uniffiCallStatus
    )
})
}
    
    /**
     * This guardian's FROST identifier, as canonical hex.
     */
open func identifier() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_identifier(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Number of sessions with live (unconsumed) round-1 nonces. `0` between
     * ceremonies; the single-use discipline is observable here.
     */
open func pendingCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_pending_count(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Round 1: commit. Mints single-use signing nonces, stores them under
     * `session_id`, and returns the `Round1Reply` message JSON the coordinator
     * expects on the relay. Throws [`StewardError::Wiped`] after [`wipe`](Self::wipe).
     */
open func round1(sessionId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_round1(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),uniffiCallStatus
    )
})
}
    
    /**
     * Round 2: sign the coordinator's `signing_package` (JSON) under the ZIP-312
     * randomizer α (`randomizer_le_hex`, 32-byte little-endian) **by value**, then
     * delete this session's nonces. Returns the `Round2Reply` message JSON. A
     * missing or already-consumed session throws [`StewardError::NoSession`].
     */
open func round2(sessionId: String, signingPackageJson: String, randomizerLeHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_round2(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(signingPackageJson),
        FfiConverterString.lower(randomizerLeHex),uniffiCallStatus
    )
})
}
    
    /**
     * Zeroize and drop all key material (the `KeyPackage` and every live nonce). The
     * handle is inert afterwards — any further round call throws
     * [`StewardError::Wiped`]. Call this on lock/logout.
     */
open func wipe()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_method_guardian_wipe(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGuardian: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Guardian

    public static func lift(_ handle: UInt64) throws -> Guardian {
        return Guardian(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Guardian) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Guardian {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Guardian, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGuardian_lift(_ handle: UInt64) throws -> Guardian {
    return try FfiConverterTypeGuardian.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGuardian_lower(_ value: Guardian) -> UInt64 {
    return FfiConverterTypeGuardian.lower(value)
}




/**
 * One guardian's share, ready to hand to that guardian (who then [`seal_share`]s
 * it under their own passphrase).
 *
 * [`seal_share`]: crate::seal_share
 */
public struct GuardianShare: Equatable, Hashable {
    /**
     * The guardian's FROST identifier, canonical hex.
     */
    public var identifierHex: String
    /**
     * The guardian's `SecretShare` as JSON — the exact bytes [`seal_share`] expects.
     *
     * [`seal_share`]: crate::seal_share
     */
    public var secretShareJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The guardian's FROST identifier, canonical hex.
         */identifierHex: String, 
        /**
         * The guardian's `SecretShare` as JSON — the exact bytes [`seal_share`] expects.
         *
         * [`seal_share`]: crate::seal_share
         */secretShareJson: String) {
        self.identifierHex = identifierHex
        self.secretShareJson = secretShareJson
    }

    

    
}

#if compiler(>=6)
extension GuardianShare: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGuardianShare: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GuardianShare {
        return
            try GuardianShare(
                identifierHex: FfiConverterString.read(from: &buf), 
                secretShareJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GuardianShare, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identifierHex, into: &buf)
        FfiConverterString.write(value.secretShareJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGuardianShare_lift(_ buf: RustBuffer) throws -> GuardianShare {
    return try FfiConverterTypeGuardianShare.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGuardianShare_lower(_ value: GuardianShare) -> RustBuffer {
    return FfiConverterTypeGuardianShare.lower(value)
}


/**
 * A freshly generated Ed25519 heartbeat keypair, returned to the owner at vault
 * setup. Record the `pubkey_hex` on the vault; keep the `secret_hex` on-device and
 * use it to sign each proof-of-life.
 */
public struct HeartbeatKey: Equatable, Hashable {
    /**
     * 32-byte Ed25519 secret-key **seed**, hex (RFC 8032; never leaves the device).
     */
    public var secretHex: String
    /**
     * 32-byte Ed25519 public key, hex — publish this on the vault record.
     */
    public var pubkeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 32-byte Ed25519 secret-key **seed**, hex (RFC 8032; never leaves the device).
         */secretHex: String, 
        /**
         * 32-byte Ed25519 public key, hex — publish this on the vault record.
         */pubkeyHex: String) {
        self.secretHex = secretHex
        self.pubkeyHex = pubkeyHex
    }

    

    
}

#if compiler(>=6)
extension HeartbeatKey: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartbeatKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartbeatKey {
        return
            try HeartbeatKey(
                secretHex: FfiConverterString.read(from: &buf), 
                pubkeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartbeatKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretHex, into: &buf)
        FfiConverterString.write(value.pubkeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartbeatKey_lift(_ buf: RustBuffer) throws -> HeartbeatKey {
    return try FfiConverterTypeHeartbeatKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartbeatKey_lower(_ value: HeartbeatKey) -> RustBuffer {
    return FfiConverterTypeHeartbeatKey.lower(value)
}


/**
 * The instruction returned by [`Guardian::handle_relay_message`] telling the app
 * what to do next. The caller just moves bytes: if `action == "send"`, POST
 * `{ to, msg_hex }` to `/session/{id}/send`; if `"none"`, there is nothing to send.
 */
public struct RelayAction: Equatable, Hashable {
    /**
     * `"send"` (there is a reply to POST) or `"none"` (adjourned / nothing to send).
     */
    public var action: String
    /**
     * Destination for the relay `SendBody.to`; `None` means the coordinator.
     */
    public var to: String?
    /**
     * The reply to POST as `SendBody.msg_hex` (hex of the `Message` JSON), or `None`.
     */
    public var msgHex: String?
    /**
     * Whether this session is finished for the guardian (stop polling it).
     */
    public var done: Bool
    /**
     * `"round1"` | `"round2"` | `"adjourn"` — for UX/logging only.
     */
    public var kind: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `"send"` (there is a reply to POST) or `"none"` (adjourned / nothing to send).
         */action: String, 
        /**
         * Destination for the relay `SendBody.to`; `None` means the coordinator.
         */to: String?, 
        /**
         * The reply to POST as `SendBody.msg_hex` (hex of the `Message` JSON), or `None`.
         */msgHex: String?, 
        /**
         * Whether this session is finished for the guardian (stop polling it).
         */done: Bool, 
        /**
         * `"round1"` | `"round2"` | `"adjourn"` — for UX/logging only.
         */kind: String) {
        self.action = action
        self.to = to
        self.msgHex = msgHex
        self.done = done
        self.kind = kind
    }

    

    
}

#if compiler(>=6)
extension RelayAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRelayAction: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RelayAction {
        return
            try RelayAction(
                action: FfiConverterString.read(from: &buf), 
                to: FfiConverterOptionString.read(from: &buf), 
                msgHex: FfiConverterOptionString.read(from: &buf), 
                done: FfiConverterBool.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RelayAction, into buf: inout [UInt8]) {
        FfiConverterString.write(value.action, into: &buf)
        FfiConverterOptionString.write(value.to, into: &buf)
        FfiConverterOptionString.write(value.msgHex, into: &buf)
        FfiConverterBool.write(value.done, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRelayAction_lift(_ buf: RustBuffer) throws -> RelayAction {
    return try FfiConverterTypeRelayAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRelayAction_lower(_ value: RelayAction) -> RustBuffer {
    return FfiConverterTypeRelayAction.lower(value)
}


/**
 * The output of [`split_authority`]: what the owner publishes + distributes.
 */
public struct VaultKeygen: Equatable, Hashable {
    /**
     * The Orchard spend-validating key `ak` (== the FROST group verifying key),
     * 32-byte hex. The signer derives the vault's UFVK / receiving address from this.
     */
    public var groupAkHex: String
    /**
     * The FROST `PublicKeyPackage` as JSON — publish this to the relay's vault record.
     */
    public var publicKeyPackageJson: String
    /**
     * One share per guardian (`n` of them), keyed by identifier.
     */
    public var shares: [GuardianShare]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The Orchard spend-validating key `ak` (== the FROST group verifying key),
         * 32-byte hex. The signer derives the vault's UFVK / receiving address from this.
         */groupAkHex: String, 
        /**
         * The FROST `PublicKeyPackage` as JSON — publish this to the relay's vault record.
         */publicKeyPackageJson: String, 
        /**
         * One share per guardian (`n` of them), keyed by identifier.
         */shares: [GuardianShare]) {
        self.groupAkHex = groupAkHex
        self.publicKeyPackageJson = publicKeyPackageJson
        self.shares = shares
    }

    

    
}

#if compiler(>=6)
extension VaultKeygen: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaultKeygen: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaultKeygen {
        return
            try VaultKeygen(
                groupAkHex: FfiConverterString.read(from: &buf), 
                publicKeyPackageJson: FfiConverterString.read(from: &buf), 
                shares: FfiConverterSequenceTypeGuardianShare.read(from: &buf)
        )
    }

    public static func write(_ value: VaultKeygen, into buf: inout [UInt8]) {
        FfiConverterString.write(value.groupAkHex, into: &buf)
        FfiConverterString.write(value.publicKeyPackageJson, into: &buf)
        FfiConverterSequenceTypeGuardianShare.write(value.shares, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultKeygen_lift(_ buf: RustBuffer) throws -> VaultKeygen {
    return try FfiConverterTypeVaultKeygen.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultKeygen_lower(_ value: VaultKeygen) -> RustBuffer {
    return FfiConverterTypeVaultKeygen.lower(value)
}


/**
 * Errors returned by the Steward mobile SDK.
 */
public 
enum StewardError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * JSON (de)serialization failed — a malformed share / package / message.
     */
    case Json(
        /**
         * Underlying serde_json message.
         */msg: String
    )
    /**
     * Hex decoding failed (bad characters, or the wrong length for a fixed field).
     */
    case Hex(
        /**
         * Underlying hex message.
         */msg: String
    )
    /**
     * Key-derivation (Argon2id) failure — e.g. invalid KDF parameters.
     */
    case Kdf(
        /**
         * Underlying KDF message.
         */msg: String
    )
    /**
     * The keystore could not be opened: **wrong passphrase or a corrupted blob**
     * (indistinguishable by design — a wrong passphrase must not be told apart
     * from tampering).
     */
    case BadPassphrase
    /**
     * A wrapped FROST error from [`steward_core`] (keygen / commit / sign / aggregate).
     */
    case Frost(
        /**
         * Underlying FROST message.
         */msg: String
    )
    /**
     * A malformed input: bad length, unknown blob version, a non-32-byte field, ...
     */
    case Format(
        /**
         * What was malformed.
         */msg: String
    )
    /**
     * The [`Guardian`](crate::Guardian) handle has been wiped; no key material remains.
     */
    case Wiped
    /**
     * No live round-1 nonces for this session (round 1 was skipped, or the nonces
     * were already consumed by a round 2 — the single-use discipline).
     */
    case NoSession
    /**
     * A guardian received a message it should never be sent (a coordinator-bound reply).
     */
    case Unexpected
    /**
     * The platform RNG failed.
     */
    case Rng(
        /**
         * Underlying RNG message.
         */msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension StewardError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStewardError: FfiConverterRustBuffer {
    typealias SwiftType = StewardError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StewardError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Json(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Hex(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Kdf(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .BadPassphrase
        case 5: return .Frost(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Format(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 7: return .Wiped
        case 8: return .NoSession
        case 9: return .Unexpected
        case 10: return .Rng(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StewardError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Json(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Hex(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Kdf(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .BadPassphrase:
            writeInt(&buf, Int32(4))
        
        
        case let .Frost(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Format(msg):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .Wiped:
            writeInt(&buf, Int32(7))
        
        
        case .NoSession:
            writeInt(&buf, Int32(8))
        
        
        case .Unexpected:
            writeInt(&buf, Int32(9))
        
        
        case let .Rng(msg):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStewardError_lift(_ buf: RustBuffer) throws -> StewardError {
    return try FfiConverterTypeStewardError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStewardError_lower(_ value: StewardError) -> RustBuffer {
    return FfiConverterTypeStewardError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGuardianShare: FfiConverterRustBuffer {
    typealias SwiftType = [GuardianShare]

    public static func write(_ value: [GuardianShare], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGuardianShare.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GuardianShare] {
        let len: Int32 = try readInt(&buf)
        var seq = [GuardianShare]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGuardianShare.read(from: &buf))
        }
        return seq
    }
}
/**
 * Open a sealed share blob into a live [`Guardian`] handle.
 *
 * Decrypts with `passphrase`, rebuilds the `KeyPackage`, and returns a handle that
 * keeps the key material inside the object (never returned to the app). A wrong
 * passphrase (or a tampered blob) throws [`StewardError::BadPassphrase`]. Unlock
 * **once** (not per relay poll); call [`Guardian::wipe`] on lock/logout.
 */
public func openGuardian(sealedBlob: String, passphrase: String)throws  -> Guardian  {
    return try  FfiConverterTypeGuardian_lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_open_guardian(
        FfiConverterString.lower(sealedBlob),
        FfiConverterString.lower(passphrase),uniffiCallStatus
    )
})
}
/**
 * Generate a fresh Ed25519 heartbeat keypair (owner setup). The secret is 32
 * random bytes from the platform CSPRNG; the public key is derived from it.
 */
public func generateHeartbeatKey() -> HeartbeatKey  {
    return try!  FfiConverterTypeHeartbeatKey_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_generate_heartbeat_key(uniffiCallStatus
    )
})
}
/**
 * Derive the hex Ed25519 public key from a hex secret seed.
 */
public func heartbeatPubkey(skHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_heartbeat_pubkey(
        FfiConverterString.lower(skHex),uniffiCallStatus
    )
})
}
/**
 * Whether the dead-man's-switch has **lapsed** at `now`, judged purely from the
 * owner's own signed timestamp: `now > latest + interval + grace` (saturating).
 * This is the authoritative inheritance gate a guardian computes on its own clock
 * from a heartbeat it verified itself — never trusting a relay's state flag.
 */
public func isLapsed(latest: UInt64, interval: UInt64, grace: UInt64, now: UInt64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_is_lapsed(
        FfiConverterUInt64.lower(latest),
        FfiConverterUInt64.lower(interval),
        FfiConverterUInt64.lower(grace),
        FfiConverterUInt64.lower(now),uniffiCallStatus
    )
})
}
/**
 * Sign a proof-of-life for `vault_id` at `time` (unix seconds) with the owner's
 * hex heartbeat secret seed. Deterministic (RFC 8032): identical inputs → identical
 * bytes. Returns the 64-byte signature as hex.
 */
public func signHeartbeat(skHex: String, vaultId: String, time: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_sign_heartbeat(
        FfiConverterString.lower(skHex),
        FfiConverterString.lower(vaultId),
        FfiConverterUInt64.lower(time),uniffiCallStatus
    )
})
}
/**
 * Verify a hex heartbeat signature against the vault's recorded hex public key and
 * the canonical message. Returns `false` — never throws — on any decode or
 * verification failure. A relay has no secret key, so it cannot forge a `true` here.
 */
public func verifyHeartbeat(pubkeyHex: String, vaultId: String, time: UInt64, sigHex: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_verify_heartbeat(
        FfiConverterString.lower(pubkeyHex),
        FfiConverterString.lower(vaultId),
        FfiConverterUInt64.lower(time),
        FfiConverterString.lower(sigHex),uniffiCallStatus
    )
})
}
/**
 * Split the vault spend authority into `t`-of-`n` guardian shares (trusted-dealer).
 *
 * `n` = total guardians, `t` = threshold (`1 <= t <= n`). If `ask_hex` is `None` a
 * fresh spend authority is generated on-device and dropped after the split (ideal
 * trusted-dealer hygiene — the monolithic key never exists anywhere afterwards). If
 * `Some`, it is the 32-byte hex of an existing RedPallas `ask` (e.g. one the signer
 * derived), so the resulting vault address matches a pre-derived one.
 *
 * The split is routed through even-Y normalization by [`steward_core::keys`], so
 * `ak` always has the even Y coordinate RedPallas/Orchard require.
 */
public func splitAuthority(n: UInt16, t: UInt16, askHex: String?)throws  -> VaultKeygen  {
    return try  FfiConverterTypeVaultKeygen_lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_split_authority(
        FfiConverterUInt16.lower(n),
        FfiConverterUInt16.lower(t),
        FfiConverterOptionString.lower(askHex),uniffiCallStatus
    )
})
}
/**
 * Seal a guardian's secret share for encrypted-at-rest storage.
 *
 * `secret_share_json` is the JSON of a [`steward_core`] `SecretShare` — exactly the
 * `GuardianShare.secret_share_json` the vault dealer produced in
 * [`split_authority`](crate::split_authority). Returns a self-describing sealed-blob
 * JSON string; store it wherever the platform keeps app data (Keychain / Keystore /
 * files). A malformed share is rejected here.
 */
public func sealShare(secretShareJson: String, passphrase: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_seal_share(
        FfiConverterString.lower(secretShareJson),
        FfiConverterString.lower(passphrase),uniffiCallStatus
    )
})
}
/**
 * Coordinator: aggregate the guardians' round-2 replies into the final 64-byte
 * RedPallas signature (hex), re-randomized by α.
 *
 * Each element of `round2_replies` is a `Round2Reply` message JSON — exactly what
 * [`Guardian::round2`](crate::Guardian::round2) returns. The result verifies against
 * `rk = ak + [α]G` (see [`verify_aggregate`]) — **not** the un-randomized group key.
 */
public func aggregateSignature(round2Replies: [String], signingPackageJson: String, sighashHex: String, randomizerLeHex: String, publicKeyPackageJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_aggregate_signature(
        FfiConverterSequenceString.lower(round2Replies),
        FfiConverterString.lower(signingPackageJson),
        FfiConverterString.lower(sighashHex),
        FfiConverterString.lower(randomizerLeHex),
        FfiConverterString.lower(publicKeyPackageJson),uniffiCallStatus
    )
})
}
/**
 * Coordinator: assemble the `SigningPackage` (JSON) over `sighash_hex` from the
 * guardians' round-1 replies.
 *
 * Each element of `round1_replies` is a `Round1Reply` message JSON — exactly what
 * [`Guardian::round1`](crate::Guardian::round1) returns. Pass the `t` you selected.
 */
public func buildSigningPackage(round1Replies: [String], sighashHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_build_signing_package(
        FfiConverterSequenceString.lower(round1Replies),
        FfiConverterString.lower(sighashHex),uniffiCallStatus
    )
})
}
/**
 * Generate a uniformly random ZIP-312 randomizer α (32-byte little-endian hex).
 *
 * **Simulation / testing only.** In production α is fixed by the transaction builder
 * (`zcash-sign`) and must be threaded by value; a freshly generated α would not
 * match the transaction's `rk` and the signature would be unusable on-chain.
 */
public func randomRandomizerHex() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_random_randomizer_hex(uniffiCallStatus
    )
})
}
/**
 * The randomized group verifying key `rk = ak + [α]G` (32-byte hex) for the given
 * randomizer and public package.
 */
public func randomizedVerifyingKeyHex(randomizerLeHex: String, publicKeyPackageJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_randomized_verifying_key_hex(
        FfiConverterString.lower(randomizerLeHex),
        FfiConverterString.lower(publicKeyPackageJson),uniffiCallStatus
    )
})
}
/**
 * Verify a 64-byte hex signature against `rk = ak + [α]G` for the given randomizer
 * and public package — the same check the coordinator does before broadcasting.
 * Returns `false` on any decode/verify failure (only structural errors throw).
 */
public func verifyAggregate(sighashHex: String, randomizerLeHex: String, publicKeyPackageJson: String, sigHex: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeStewardError_lift) {
        uniffiCallStatus in
    uniffi_steward_ffi_fn_func_verify_aggregate(
        FfiConverterString.lower(sighashHex),
        FfiConverterString.lower(randomizerLeHex),
        FfiConverterString.lower(publicKeyPackageJson),
        FfiConverterString.lower(sigHex),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_steward_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_steward_ffi_checksum_func_open_guardian() != 50376) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_generate_heartbeat_key() != 35325) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_heartbeat_pubkey() != 38735) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_is_lapsed() != 18647) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_sign_heartbeat() != 30508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_verify_heartbeat() != 53228) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_split_authority() != 35616) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_seal_share() != 59710) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_aggregate_signature() != 63799) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_build_signing_package() != 30401) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_random_randomizer_hex() != 61912) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_randomized_verifying_key_hex() != 32116) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_func_verify_aggregate() != 16335) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_adjourn() != 16491) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_handle_relay_message() != 36894) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_identifier() != 42066) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_pending_count() != 13566) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_round1() != 19253) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_round2() != 51063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_steward_ffi_checksum_method_guardian_wipe() != 48537) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureStewardFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all