name: Builder for Linux Flatpak

on:
  workflow_dispatch:

jobs:
  build:
    name: Image Builder for flatpak-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/Dockerfile-builder-flatpak
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/zwallet_builder_flatpak:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
