"""description of changes

Revision ID: 32a500b220e7
Revises: 0884acf0cc48
Create Date: 2024-10-05 10:25:40.828561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a500b220e7'
down_revision: Union[str, None] = '0884acf0cc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 't')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('t', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
