arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: messages.dart
output-dir: lib/generated/intl
synthetic-package: false
output-class: S
nullable-getter: false
untranslated-messages-file: missing.arb
