"""description of changes

Revision ID: 6778724b102c
Revises: e6a4c3bcaf02
Create Date: 2024-10-05 10:28:14.882898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6778724b102c'
down_revision: Union[str, None] = 'e6a4c3bcaf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'w')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('w', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
