name: Auto Revalidate Vercel Cache

on:
  push:
    branches: [ main ]
    paths:
      - "site/**/*.md"
      - "site/**/*.mdx"

jobs:
  revalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel revalidation
        run: |
          curl -G "https://zechub.wiki/api/revalidate" \
            --data-urlencode "secret=${{ secrets.REVALIDATE_SECRET }}" \
            -H "Content-Type: application/json"
